### ISSUE TITLE
Cors Error in the Api

### ISSUE THREAD

**Issue by sakshamjaiswal1** [ThotaRitikesh/MyTube#1]
![image](https://github.com/ThotaRitikesh/MyTube/assets/75566599/80fce823-4cae-4445-8fe9-3bd93649416f)

There is a cors error while send request u can fix it when u r free to make this project better.
Feel free to ask if you want any help

**Comment by ThotaRitikesh** [comment]
Thank you for your response .Actually I didn't get the proper api without
the cors header.That's the reason I left it unfixed and added a note to use
cors extension in the description.

**Comment by ThotaRitikesh** [comment]
Thank you for your response .Actually I didn't get the proper api without
the cors header.That's the reason I left it unfixed and added a note to use
cors extension in the description.I'll try to fix it if i find any proper
api asap.

**Comment by sakshamjaiswal1** [comment]
![image](https://github.com/ThotaRitikesh/MyTube/assets/75566599/4427e4c7-4cb7-47b6-bf56-ddb23f1e4bff)

here you have hardcdoed the client (firefox in this case) u can make it  dynamic to make this error gone

**Comment by ThotaRitikesh** [comment]
cros error solved.
